version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    env_file:
      - ./node/.env
    networks:
      - nodenet
    #volumes:
    #  - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    ports:
      - 3000:3000

  db:
    build:
      context: mysql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=mysql_pass      
    networks:
      - nodenet

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  nodenet:   
    driver: bridge